name: Install shared software dependencies

inputs:
    os:
        description: "The current operating system"
        required: true
        type: string
        options:
            - amazon-linux
            - macos
            - ubuntu
    target:
        description: "Specified target for rust toolchain, ex. x86_64-apple-darwin"
        type: string
        required: false
        defalt: "x86_64-unknown-linux-gnu"
        options:
            - x86_64-unknown-linux-gnu
            - aarch64-unknown-linux-gnu
            - aarch64-unknown-linux-musl
            - x86_64-apple-darwin
            - aarch64-apple-darwin
    github-token:
        description: "GITHUB_TOKEN, GitHub App installation access token"
        required: true
        type: string

runs:
    using: "composite"
    steps:
        - name: Install software dependencies for macOS
          shell: bash
          if: "${{ inputs.os == 'macos' }}"
          run: |
              brew update
              brew upgrade || true
              brew install git gcc pkgconfig openssl redis coreutils

        - name: Install software dependencies for Ubuntu GNU
          shell: bash
          if: "${{ inputs.os == 'ubuntu' }}"
          run: |
              sudo apt update -y
              sudo apt install -y git gcc pkg-config openssl libssl-dev

        - name: Install software dependencies for Amazon-Linux
          shell: bash
          if: "${{ inputs.os == 'amazon-linux' }}"
          run: |
              yum install -y gcc pkgconfig openssl openssl-devel which curl redis6 gettext --allowerasing

        - name: Install software dependencies for Ubuntu MUSL
          shell: sh
          if: "${{ inputs.os == 'ubuntu-latest-musl' }}"
          run: |
              apk update
              wget -O - https://sh.rustup.rs | sh -s -- -y
              source "$HOME/.cargo/env"
              apk add protobuf-dev musl-dev make gcc


        - name: Install Rust toolchain
          if: "${{ inputs.os != 'ubuntu-latest-musl' }}"
          uses: dtolnay/rust-toolchain@stable
          with:
              targets: ${{ inputs.target }}

        - name: Install protoc (protobuf)
          if: "${{ inputs.os != 'ubuntu-latest-musl' }}"
          uses: arduino/setup-protoc@v3
          with:
              version: "25.1"
              repo-token: ${{ inputs.github-token }}
