name: Build Node wrapper

inputs:
    os:
        description: "The current operating system"
        required: true
        type: string
        options:
            - macOS
            - ubuntu
            - amazon-linux
            - macos-latest
            - ubuntu-latest
    target:
        description: "The platform target, for example x86_64-unknown-linux-gnu"
        required: false
        type: string
        default: ""

    release_mode:
        description: "Enable building the wrapper in release mode"
        required: false
        type: boolean
        default: "false"

env:
    CARGO_TERM_COLOR: always

runs:
    using: "composite"
    steps:
        - name: Install software dependencies
          uses: ./.github/workflows/install-shared-dependencies
          with:
              os: ${{ inputs.os }}

        - name: npm install
          shell: bash
          working-directory: ./node
          run: |
              ARCH_FLAG=`if [ ${{ inputs.target  == 'aarch64-unknown-linux-gnu' }} ]; then echo "--arch=arm64"; fi`
              rm -rf node_modules && npm install $ARCH_FLAG --frozen-lockfile
              cd rust-client
              npm install

        - name: Build
          shell: bash
          working-directory: ./node
          run: |
              source "$HOME/.cargo/env"
              TARGET_FLAG=`if [ "${{ inputs.target }}" != ''  ]; then echo "--target ${{ inputs.target }}"; fi`
              npm run build --build-flags="$TARGET_FLAG"
