name: Install Valkey

inputs:
    engine-version:
        description: "valkey version to install"
        required: true
        type: string
    target:
        description: "Specified target toolchain, ex. x86_64-unknown-linux-gnu"
        type: string
        required: true
        options:
            - x86_64-unknown-linux-gnu
            - aarch64-unknown-linux-gnu
            - x86_64-apple-darwin
            - aarch64-apple-darwin
            - aarch64-unknown-linux-musl
            - x86_64-unknown-linux-musl

env:
    CARGO_TERM_COLOR: always
    VALKEY_MIN_VERSION: "7.2.5"

runs:
    using: "composite"

    steps:
        - name: Cache Valkey
          uses: actions/cache@v4
          id: cache-valkey
          with:
            path: |
                ~/valkey
            key: valkey-${{ inputs.engine-version }}-${{ inputs.target }}

        - name: Build Valkey
          if: ${{ steps.cache-valkey.outputs.cache-hit != 'true' }}
          shell: bash
          run: | 
            echo "Building valkey ${{ inputs.engine-version }}"
            cd ~
            git clone https://github.com/valkey-io/valkey.git
            cd valkey
            git checkout ${{ inputs.engine-version }}
            make BUILD_TLS=yes

        - name: Install Valkey
          shell: bash
          run: |
            cd ~/valkey
            sudo make install
            echo 'export PATH=/usr/local/bin:$PATH' >>~/.bash_profile

        - name: Check if it's a Valkey released version
          shell: bash
          id: version_calc
          run: |
            VALKEY_MIN_VER_CLEAN=`echo "7.2.5" | tr -dc '0-9'`
            CURR_VER_CLEAN=`echo ${{ inputs.engine-version }} | tr -dc '0-9'`
            if [[ $CURR_VER_CLEAN -lt 100 ]]; then CURR_VER_CLEAN=`echo $(($CURR_VER_CLEAN * 10))`; fi
            if [[ $CURR_VER_CLEAN -ge $VALKEY_MIN_VER_CLEAN ]]; then
                VALKEY_RELEASE=true
            else
                VALKEY_RELEASE=false

        - name: Check if the current version is a Valkey release
          id: is_valkey_release
          uses: ./.github/actions/compare-versions
          with:
              version1: ${{ inputs.engine-version }}
              version2: ${{ env.VALKEY_MIN_VERSION }}

        - name: Display comparison result
          shell: bash
          run: |
            echo "Comparison result: ${{ steps.is_valkey_release.outputs.result }}"

        - name: Verify Valkey installation and symlinks
          shell: bash
          run: | 
            IS_VALKEY=${{ steps.is_valkey_release.outputs.result }}
            EXPECTED_VERSION=`echo ${{ inputs.engine-version }} | sed -e "s/^redis-//"`
            REDIS_SERVER_VER=$(redis-server -v)
            if [[ $IS_VALKEY == "true" ]]; then
                # Prior to the minimum Valkey version, only redis-server is installed
                VALKEY_SERVER_VER=$(valkey-server -v)
                INSTALLED_VER=$VALKEY_SERVER_VER
            else
                INSTALLED_VER=$REDIS_SERVER_VER
            fi

            if [[ $IS_VALKEY == true ]] && [[ $VALKEY_SERVER_VER != $REDIS_SERVER_VER ]]; then
                echo $'Symlink from valkey to redis failed.' \
                $'\nvalkey: '"$VALKEY_SERVER_VER"$', path:'"$(which valkey-server)" \
                $'\nredis: '"$REDIS_SERVER_VER"$', path:'"$(which redis-server)"
                exit 1
            elif [[ $INSTALLED_VER != *"${EXPECTED_VERSION}"* ]]; then
                echo "Wrong version has been installed. Expected: $EXPECTED_VERSION, Installed: $INSTALLED_VER"
                exit 1
            else
                echo "Successfully installed the server: $INSTALLED_VER"
            fi
 
