name: Install Valkey

inputs:
    engine-version:
        description: "Engine version to install"
        required: true
        type: string
    target:
        description: "Specified target toolchain, ex. x86_64-unknown-linux-gnu"
        type: string
        required: true
        options:
            - x86_64-unknown-linux-gnu
            - aarch64-unknown-linux-gnu
            - x86_64-apple-darwin
            - aarch64-apple-darwin
            - aarch64-unknown-linux-musl
            - x86_64-unknown-linux-musl

env:
    CARGO_TERM_COLOR: always
    VALKEY_MIN_VERSION: "7.2.5"

runs:
    using: "composite"

    steps:
        - name: Cache Valkey
           # TODO: remove the musl ARM64 limitation when https://github.com/actions/runner/issues/801 is resolved
          if: ${{ inputs.target != 'aarch64-unknown-linux-musl' }}
          uses: actions/cache@v4
          id: cache-valkey
          with:
            path: |
                ~/valkey
            key: valkey-${{ inputs.engine-version }}-${{ inputs.target }}

        - name: Build Valkey
          if: ${{ steps.cache-valkey.outputs.cache-hit != 'true' }}
          shell: bash
          run: | 
            echo "Building valkey ${{ inputs.engine-version }}"
            cd ~
            rm -rf valkey
            git clone https://github.com/valkey-io/valkey.git
            cd valkey
            git checkout ${{ inputs.engine-version }}
            make BUILD_TLS=yes

        - name: Install Valkey
          shell: bash
          run: |
            cd ~/valkey
            if command -v sudo &> /dev/null
            then
                echo "sudo command exists"
                sudo make install
            else
                echo "sudo command does not exist"
                make install
            fi
            echo 'export PATH=/usr/local/bin:$PATH' >>~/.bash_profile

        - name: Check if the current version is a Valkey release
          id: is_valkey_release
          uses: ./.github/workflows/compare-versions
          with:
              # Checks if the current tested version is a Valkey release (>= 7.2.5)
              version1: ${{ inputs.engine-version }}
              version2: ${{ env.VALKEY_MIN_VERSION }}

        - name: Verify Valkey installation and symlinks
          shell: bash
          run: | 
            # In Valkey releases, the engine is built with symlinks from valkey-server and valkey-cli
            # to redis-server and redis-cli. This step ensures that the engine is properly installed
            # with the expected version and that Valkey symlinks are correctly created.

            IS_VALKEY=${{ steps.is_valkey_release.outputs.result }}
            EXPECTED_VERSION=`echo ${{ inputs.engine-version }} | sed -e "s/^redis-//"`
            REDIS_SERVER_VER=$(redis-server -v)
            if [[ $IS_VALKEY == "true" ]]; then
                echo "Is a Valkey version"
                # Prior to the minimum Valkey version, only redis-server is installed
                VALKEY_SERVER_VER=$(valkey-server -v)
                INSTALLED_VER=$VALKEY_SERVER_VER
            else
                echo "Isn't a Valkey version"
                INSTALLED_VER=$REDIS_SERVER_VER
            fi

            if [[ $IS_VALKEY == true ]] && [[ $VALKEY_SERVER_VER != $REDIS_SERVER_VER ]]; then
                echo $'Symlink from valkey to redis failed.' \
                $'\nvalkey: '"$VALKEY_SERVER_VER"$', path:'"$(which valkey-server)" \
                $'\nredis: '"$REDIS_SERVER_VER"$', path:'"$(which redis-server)"
                exit 1
            elif [[ $INSTALLED_VER != *"${EXPECTED_VERSION}"* ]]; then
                echo "Wrong version has been installed. Expected: $EXPECTED_VERSION, Installed: $INSTALLED_VER"
                exit 1
            else
                echo "Successfully installed the server: $INSTALLED_VER"
            fi
 
