name: Build Python wrapper

inputs:
    os:
        description: "The current operating system"
        required: true
        type: string
        options:
          - macOS
          - ubuntu
          - amazon-linux
    release_mode:
        description: "Enable building the wrapper in release mode"
        required: false
        type: boolean
        default: 'false'

env:
    CARGO_TERM_COLOR: always

runs:
    using: "composite"
    steps:        
        - name: Install software dependencies
          uses: ./.github/workflows/install-shared-dependencies
          with:
              os: ${{ inputs.os }}

        - name: Install Python software dependencies
          shell: bash
          run: |
              python3 -m ensurepip --upgrade
              python3 -m pip install --upgrade pip
              python3 -m pip install virtualenv mypy-protobuf

        - name: Generate protobuf files
          shell: bash
          working-directory: .
          run: |
              export PATH="$PATH:$HOME/.local/bin"
              MYPY_PROTOC_PATH=`which protoc-gen-mypy`
              protoc --plugin=protoc-gen-mypy=${MYPY_PROTOC_PATH} -Iprotobuf=./babushka-core/src/protobuf/ --python_out=./python/python/pybushka --mypy_out=./python/python/pybushka ./babushka-core/src/protobuf/*.proto

        - name: Build Pybushka
          shell: bash
          working-directory: ./python
          run: |
              source "$HOME/.cargo/env"
              python3 -m venv .env
              source .env/bin/activate
              python3 -m pip install --upgrade pip
              python3 -m pip install -r requirements.txt
              RELEASE_FLAG=`if [ ${{ inputs.release_mode }} = 'true'  ]; then echo --release; fi`
              maturin develop ${RELEASE_FLAG}
