# TODO: Investigate using uniffi bindings for Go instead of cbindgen
language = "C"

header = "/* Copyright GLIDE-for-Redis Project Contributors - SPDX Identifier: Apache-2.0 */"

[parse]
parse_deps = true
include = ["glide-core"] 
