[package]
name = "pybushka"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Amazon Web Services"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pybushka"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "^0.19", features = ["extension-module"] }
pyo3-asyncio = { version =  "^0.19", features = ["tokio-runtime"] }
redis = { path = "../submodules/redis-rs/redis", features = ["aio", "tokio-comp", "connection-manager", "tls", "tokio-rustls-comp"] }
babushka = { path = "../babushka-core" }
tokio = { version = "^1", features = ["rt", "macros", "rt-multi-thread", "time"] }
logger_core = {path = "../logger_core"}
tracing-subscriber = "0.3.16"

[package.metadata.maturin]
python-source = "python"

[profile.release]
lto = true
debug = true
