[build-system]
requires = ["maturin>=0.13,<0.14"]
build-backend = "maturin"

[tool.isort]
profile = "black"

[tool.flake8]
max-complexity = 12
max-line-length = 127
extend-ignore = ['E203']

[tool.black]
target-version = ['py38', 'py39', 'py310', 'py311']

[project.option-dependencies]
test = [
    "hypothesis",
    "sympy"
]

[project]
name = "babushka"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
