[package]
name = "babushka_js"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Amazon Web Services"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
redis = { path = "../../submodules/redis-rs/redis", features = ["aio", "tokio-comp", "tls", "tokio-rustls-comp"] }
babushka = { path = "../../babushka-core" }
tokio-util = { version = "0.7", optional = true }
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread", "time"] }
napi = {version = "2.14", features = ["napi4", "napi6"] }
napi-derive = "2.14"
logger_core = {path = "../../logger_core"}
tracing-subscriber = "0.3.16"
byteorder = "1.4.3"



[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
debug = true
