[package]
authors = ["Shachar Langbeheim <shachlan@amazon.com>"]
edition = "2021"
name = "babushka_js"
version = "0.1.0"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3.21"
redis = { path = "../../redis-rs", features = ["aio", "tokio-comp"] }
tokio-util = { version = "0.7", optional = true }
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread", "time"] }
stopwatch = "0.0.7"
timer = "0.2.0"
rand = "0.8.5"
libffi = "3.0.0"
napi = {version = "2", features = ["tokio_rt"] }
napi-derive = "2"
byteorder = "1.4.3"
lifeguard = "0.6.1"

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true
debug = true
