name: C# tests

on:
  push:
    branches: ["main"]
    paths:
      - csharp/**
      - redis-rs/**
  pull_request:
    paths:
      - csharp/**
      - redis-rs/**

permissions:
  contents: read

jobs:
  lint-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/lint-rust
        with:
          cargo-toml-folder: ./csharp/lib
