name: foobar
on:
    push:
        branches: ["main"]
    pull_request:
        paths:
            - .github/workflows/**   

env:
    CARGO_TERM_COLOR: always
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - name: print
        run: |
            echo "1"
            echo ${GITHUB_WORKSPACE}
            echo "2"
            echo ${{GITHUB_WORKSPACE}}
