name: foobar
on:
    push:
        branches: ["main"]
        paths:
            - .github/workflows/**   
            - temp/**        
    pull_request:
        paths:
            - .github/workflows/**   
            - temp/**

env:
    CARGO_TERM_COLOR: always
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - name: print1
        run: echo "1"
      - name: print2        
        run: echo ${GITHUB_WORKSPACE}
      - name: print3        
        run: echo "2"
      - name: print4        
        run: echo "2"
      - name: print5        
        run: echo ${{GITHUB_WORKSPACE}}
