name: Java client benchmarks

on:
  workflow_dispatch:
    inputs:
      name:
        required: false
        type: string

run-name: ${{ inputs.name == '' && format('{0} @ {1}', github.ref_name, github.sha) || inputs.name }}

jobs:
  java-benchmark:
    strategy:
      matrix:
        java:
          - 11
          - 17
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}

      - name: Start Redis
        run: docker run -p 6379:6379 -p 8001:8001 -d redis/redis-stack

      - name: Run benchmarks
        working-directory: java
        run: ./gradlew :benchmark:run

      - name: Upload test reports
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: test-reports-${{ matrix.java }}
          path: |
            java/benchmarks/build/reports/**
