name: Java CI

on:
    push:
        branches: ["main"]
        paths:
            - babushka-core/**
            - submodules/**
            - "java/**"
            - ".github/workflows/java.yml"
    pull_request:
        paths:
            - babushka-core/**
            - submodules/**
            - "java/**"
            - ".github/workflows/java.yml"

# Run only most latest job on a branch and cancel previous ones
concurrency:
    group: ${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
    build-and-test-java-client:
        strategy:
            # Run all jobs
            fail-fast: false
            matrix:
                java:
                    - 11
                    - 17
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Set up JDK ${{ matrix.java }}
              uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: ${{ matrix.java }}

            - name: Install protoc (protobuf)
              run: |
                  sudo apt update
                  sudo apt install -y protobuf-compiler

            - name: Build rust part
              working-directory: java
              run: cargo build --release

            - name: Start Redis
              run: docker run -p 6379:6379 -p 8001:8001 -d redis/redis-stack

            - name: Build java part
              working-directory: java
              run: ./gradlew --continue build

            - name: Upload test reports
              if: always()
              continue-on-error: true
              uses: actions/upload-artifact@v3
              with:
                  name: test-reports-${{ matrix.java }}
                  path: |
                      java/client/build/reports/**
                      java/integTest/build/reports/**
