name: Java client benchmarks

on:
    workflow_dispatch:
        inputs:
            name:
                required: false
                type: string

run-name: ${{ inputs.name == '' && format('{0} @ {1}', github.ref_name, github.sha) || inputs.name }}

jobs:
    java-benchmark:
        timeout-minutes: 25
        strategy:
            # Run all jobs
            fail-fast: false
            matrix:
                java:
                    - 11
                    - 17
                redis:
                    - 6.2.14
                    - 7.2.3
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Set up JDK ${{ matrix.java }}
              uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: ${{ matrix.java }}

            - name: Install redis
              uses: ./.github/workflows/install-redis
              with:
                  redis-version: ${{ matrix.redis }}

            - name: benchmark
              uses: ./.github/workflows/test-benchmark
              #   TODO - enable once benchmark works
              if: ${{ false }}
              with:
                  language-flag: -java

            - name: Upload test reports
              if: always()
              continue-on-error: true
              uses: actions/upload-artifact@v3
              with:
                  name: test-reports-${{ matrix.java }}
                  path: |
                      java/benchmarks/build/reports/**
