name: lint-ts
on:
    push:
        branches: ["main"]
        paths:
            - benchmarks/node/**
            - node/**
    pull_request:
        paths:
            - benchmarks/node/**
            - node/**

env:
    CARGO_TERM_COLOR: always
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - name: lint ts
        run: |
            npm install @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint typescript
            npm i
            npx eslint .
