name: Node

on:
    push:
        branches: ["main"]
        paths:
            - redis-rs/**
            - node/**
    pull_request:
        paths:
            - redis-rs/**
            - node/**

env:
    CARGO_TERM_COLOR: always

jobs:
    lint-rust:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/workflows/lint-rust
              with:
                  cargo-toml-folder: ./node/rust-client
