name: Node

on:
    push:
        branches: ["main"]
        paths:
            - babushka-core/**
            - submodules/**
            - node/**
            - utils/cluster_manager.py
    pull_request:
        paths:
            - babushka-core/src/**
            - submodules/**
            - node/**
            - utils/cluster_manager.py

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        strategy:
            fail-fast: false
            matrix:
                redis:
                    - 6.2.4
                    - 7.2.0

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install redis
              uses: ./.github/workflows/install-redis
              with:
                  redis-version: ${{ matrix.redis }}

            - name: Install protoc
              run: |
                  sudo apt update
                  sudo apt install protobuf-compiler

            - name: Use Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: npm install and test
              run: |
                  rm -rf node_modules && npm install --frozen-lockfile
                  npm install
              working-directory: ./node/rust-client

            - name: build
              run: |
                  rm -rf node_modules && npm install --frozen-lockfile
                  npm run build
              working-directory: ./node

            - name: test
              run: npm test
              working-directory: ./node

    lint-rust:
        timeout-minutes: 15
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - uses: ./.github/workflows/lint-rust
              with:
                  cargo-toml-folder: ./node/rust-client
              name: lint node rust
