name: Node

on:
    push:
        branches: ["main"]
        paths:
            - babushka-core/**
            - submodules/**
            - node/**
    pull_request:
        paths:
            - babushka-core/src/**
            - submodules/**
            - node/**

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                redis:
                    - 6.2.4

        steps:
            - uses: actions/checkout@v3
              with:
                submodules: recursive

            - name: Install redis
              uses: ./.github/workflows/install-redis
              with:
                  redis-version: ${{ matrix.redis }}
            
            - name: Install protoc
              run: |
                sudo apt update
                sudo apt install protobuf-compiler

            - name: Use Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - run: |
                  rm -rf node_modules && npm install --frozen-lockfile
                  npm install
              working-directory: ./node/rust-client

            - run: |
                  rm -rf node_modules && npm install --frozen-lockfile
                  npm install
                  npm run build
              working-directory: ./node

            - run: |
                  rm -rf node_modules && npm install --frozen-lockfile
                  npm test
              working-directory: ./node

    lint-rust:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                submodules: recursive

            - uses: ./.github/workflows/lint-rust
              with:
                  cargo-toml-folder: ./node/rust-client
