name: Python tests

on:
    push:
        branches: ["main"]
        paths:
            - python/**
            - glide-core/src/**
            - submodules/**
            - utils/cluster_manager.py
            - .github/workflows/python.yml
            - .github/workflows/build-python-wrapper/action.yml
            - .github/workflows/install-shared-dependencies/action.yml
            - .github/workflows/install-redis-modules/action.yml
            - .github/workflows/create-ec-cluster/action.yml

    pull_request:
        paths:
            - python/**
            - glide-core/src/**
            - submodules/**
            - utils/cluster_manager.py
            - .github/workflows/python.yml
            - .github/workflows/build-python-wrapper/action.yml
            - .github/workflows/install-shared-dependencies/action.yml
            - .github/workflows/install-redis-modules/action.yml
            - .github/workflows/create-ec-cluster/action.yml

concurrency:
    group: python-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    test-ubuntu-latest:
        runs-on: ubuntu-latest
        timeout-minutes: 25
        strategy:
            fail-fast: false
            matrix:
                redis:
                    - 6.2.14
                    - 7.2.3

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install redis
              uses: ./.github/workflows/install-redis
              with:
                  redis-version: ${{ matrix.redis }}

            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
              

            - name: Install dependencies
              working-directory: ./python
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8 isort black mypy-protobuf

                
            - name: Start self hosted EC2 runner
              uses: ./.github/workflows/start-self-hosted-runner
              with:
                            aws-access-key-id: ${{ secrets.AWS_EC2_ACCESS_KEY_ID }}
                            aws-secret-access-key: ${{ secrets.AWS_EC2_SECRET_ACCESS_KEY }}
                            aws-region: ${{ secrets.AWS_REGION }}
                            ec2-instance-id: ${{ secrets.AWS_EC2_INSTANCE_ID }}
            
            - name: Check AWS_ACCESS_KEY_ID
              shell: bash
              run: |
                echo shoham
                echo $AWS_ACCESS_KEY_ID

            - name: Install ec cluster
              uses: ./.github/workflows/create-ec-cluster
              with:
                aws-region: ${{ secrets.AWS_REGION }}
            - name: Lint with isort
              working-directory: ./python
              run: |
                  isort . --profile black --check --diff

            - name: Lint with flake8
              working-directory: ./python
              run: |
                  # stop the build if there are Python syntax errors or undefined names
                  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --extend-ignore=E230 --exclude=python/glide/protobuf,.env/*
                  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                  flake8 . --count --exit-zero --max-complexity=12 --max-line-length=127 --statistics --extend-ignore=E230 --exclude=python/glide/protobuf,.env/*

            - name: Lint with black
              working-directory: ./python
              run: |
                  black --check --diff .

            - name: Type check with mypy
              working-directory: ./python
              run: |
                  # The type check should run inside the virtual env to get
                  # all installed dependencies and build files
                  source .env/bin/activate
                  pip install mypy types-protobuf
                  # Install the benchmark requirements 
                  pip install -r ../benchmarks/python/requirements.txt
                  python -m mypy ..

            - name: Install Redis Modules
              uses: ./.github/workflows/install-redis-modules
              with:
                  redis-version: ${{ matrix.redis }} 

            - name: Test with pytest
              working-directory: ./python
              run: |
                  source .env/bin/activate
                  cd python/tests/
                  pytest --asyncio-mode=auto --override-ini=addopts= --load-module=$GITHUB_WORKSPACE/redisjson.so

            - uses: ./.github/workflows/test-benchmark
              with:
                  language-flag: -python
            
            
    
            
