name: Rust tests

on:
    push:
        branches: [main]
        paths:
            - logger_core/**
            - babushka-core/**
            - submodules/**
    pull_request:
        paths:
            - logger_core/**
            - babushka-core/**
            - submodules/**

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                redis:
                    - 6.2.4
                    - 7.0.0

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Install redis
              uses: ./.github/workflows/install-redis
              with:
                  redis-version: ${{ matrix.redis }}
            
            - name: Install protoc
              run: |
                sudo apt update
                sudo apt install protobuf-compiler

            - name: Install toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
                  components: rustfmt

            - uses: Swatinem/rust-cache@v1

            - name: Run tests
              working-directory: ./babushka-core
              run: cargo test -- -Z unstable-options --report-time

            - name: Check features
              working-directory: ./babushka-core
              run: |
                  cargo check --benches --all-features
                  cargo check --no-default-features

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - uses: ./.github/workflows/lint-rust
              with:
                  cargo-toml-folder: ./babushka-core

            - uses: ./.github/workflows/lint-rust
              with:
                  cargo-toml-folder: ./logger_core
