name: Rust tests

on:
    push:
        branches: [main]
        paths:
            - redis-rs/**
    pull_request:
        paths:
            - redis-rs/**

env:
    CARGO_TERM_COLOR: always

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/workflows/lint-rust
              with:
                  cargo-toml-folder: ./redis-rs
